### ISSUE TITLE
Chrome dev tool no longer support background-image

### ISSUE THREAD

**Issue by ImBobby** [astoilkov/console-powers#15]
fyi, [Found an issue from console.image](https://github.com/adriancooney/console.image/issues/13). I haven't tested but I think it might affect `console.message().image`.

**Comment by astoilkov** [comment]
Yeah. Indeed. I would investigate a little to try and find another solution.

**Comment by astoilkov** [comment]
I have tried a lot of things but the browsers have blacklisted too many properties. I created an issue to remove the method as it is no longer possible to show images in the console. https://github.com/astoilkov/console.message/issues/16
