### ISSUE TITLE
Why make console.message a function?

### ISSUE THREAD

**Issue by eorroe** [astoilkov/console-powers#2]
Instead of making `console.message()` so that you can do `console.message().text()` why not have it be: `console.message.text()`?

Glancing at your source code, I believe it'll be a simple change at the end to:

``` JS
window.console.message = new ConsoleMessage();
```

**Comment by anupsaund** [comment]
@eorroe  - Neat suggestion.
Try forking it - then pull request it back in?

It gives @astoilkov  a chance to test it that way.

**Comment by astoilkov** [comment]
That's interesting. I am not making it a function because of two reasons:
- Consistency. Every method is a function and I think it is easier to remember this way. ...and it looks consistent :)
- If there is no function call you won't be creating `ConsoleMessage` objects every time. This limits the scenario when you create two instances of a message and do something with them at the same time.

``` javascript
var messageA = console.message();
var messageB = console.message();

// do something with both messages
```

**Comment by eorroe** [comment]
Typo:

> I am not making it a function because of two reasons:

You are making it a function because .....

Anywho I've never used this, I saw it on twitter and decided to take a look at this. Therefore I didn't know that's how it was used, I thought it was a one function call thing. Didn't know you'll use it that way instantiating (I think that's a word to use) 2 different messages.

So ok just wanted to put it out there so I guess you can close this if you want.

**Comment by astoilkov** [comment]
I was telling you the reasons because you could have а good argument against my theories.

Thanks for the idea and feedback. Much appreciated.

Have a great day.

**Comment by eorroe** [comment]
The only thing you could do is make it a `getter` but that's a horrible idea (it'll look like)

``` JS
var messageA = console.message;
var messageB = console.message;
```

And they both return new Messages, therefore the following still returns a new message:

``` JS
console.message.text(); // console.message still returns a new one
```

But again that's bad practice because when you want an instance of a new constructor it should be a function call: `console.message()`.

So no, but just letting you know.

Thanks you have a good day too. :)
