### ISSUE TITLE
.group() documentation is wrong?

### ISSUE THREAD

**Issue by rtpHarry** [astoilkov/console-powers#4]
The readme.md group() documentation says:

```
Begins a group. By default the group is expanded. Provide true if you want the group to be collapsed.
```

The console.message.js says at line 50:

```
Begins a group. By default the group is expanded. Provide true if you want the group to be collapsed.
```

But the code says:

```
type: expanded === false ? 'groupCollapsed' : 'group',
```

So the documentation should both say `Provide false if you want the group to be collapsed`, right?

**Comment by astoilkov** [comment]
You are correct. I made some API changes and this is the result of it. I haven't fix the comments everywhere. You could create a pull request for that otherwise I can fix it.

Have a nice day. :)
