### ISSUE TITLE
group seems to break in electron

### ISSUE THREAD

**Issue by dashed** [astoilkov/console-powers#8]
for [electron-prebuilt@0.27.2](https://github.com/mafintosh/electron-prebuilt)

using:

``` js
console.message()
    // pass false if you want to create a collapsed group
    .group()
    .text('The group header text')
    .line()
    .line('The group content')
    .groupEnd()
    .print();
```

![screen shot 2015-06-05 at 9 04 40 am](https://cloud.githubusercontent.com/assets/139499/8006446/f422609e-0b61-11e5-9247-150997a5ae54.png)

**Comment by astoilkov** [comment]
Actually the example is not correct. I have fixed it in the readme.md. Instead of creating a new line the second time it should be test in order to render the text.

``` javascript
console.message()
    // pass false if you want to create a collapsed group
    .group()
    .text('The group header text')
    .line()
    .text('The group content')
    .groupEnd()
    .print();
```

**Comment by dashed** [comment]
I see.

---

`.groupEnd()` seems to bork a bit.

``` js
console.message()
    // pass false if you want to create a collapsed group
    .group()
    .text('The group header text')
    .line()
    .text('The group content')
    .groupEnd()
    .print();

console.message()
    // pass false if you want to create a collapsed group
    .group()
    .text('The group header text')
    .line()
    .text('The group content')
    .groupEnd()
    .print();
```

![screen shot 2015-06-05 at 9 12 10 am](https://cloud.githubusercontent.com/assets/139499/8006550/fcaac944-0b62-11e5-902c-d255038aed29.png)

---

This works:

``` js
console.message()
    // pass false if you want to create a collapsed group
    .group()
    .text('The group header text')
    .line()
    .text('The group content')
    .groupEnd()
    .print();

console.groupEnd();

console.message()
    // pass false if you want to create a collapsed group
    .group()
    .text('The group header text')
    .line()
    .text('The group content')
    .groupEnd()
    .print();
```

![screen shot 2015-06-05 at 9 12 46 am](https://cloud.githubusercontent.com/assets/139499/8006562/1d248bec-0b63-11e5-9c9c-05ad1f1a2c55.png)

**Comment by astoilkov** [comment]
Created an [issue](https://github.com/astoilkov/console.message/issues/9) and fixed it. Thank you.
